version: '2.1'
services:
  helloworlddb:
    container_name: helloworlddb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'username'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3000:3306'
    expose:
      - '3306'
    networks:
      - restapi
    volumes:
      - ./my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]



  helloworldapi:
    container_name: helloworldapi
    image: "helloworldapi"
    ports:
      - 80:80
    networks:
      - restapi
    depends_on:
      helloworlddb: { condition: service_healthy }

volumes:
  my-db:


networks:
  restapi:
    driver: bridge
