---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "helloworld.fullname" .}}-service
  namespace: {{ .Values.NAMESPACE }}
  labels:
    name: {{ template "helloworld.fullname" .}}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: {{ template "helloworld.fullname" .}}
  type: Ingress
